name: Cypress Tests

on:
  push:
    branches:
      - testes-cy

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Geral
        uses: actions/checkout@v4
        
      - name: Install
        run: npm install
       

      - name: Checkout Server
        uses: actions/checkout@v4
        with:
          path: server

      - name: Install Server
        run: |
          cd server
          npm install &

      - name: Checkout Web
        uses: actions/checkout@v4
        with:
          path: web
      
      - name: Install Web
        run: |
          cd web
          npm install
      
      - name: Configurar VariÃ¡vel de Ambiente
        run: echo "DB_ENV=${{ secrets.DB_ENV }}" > server/.env

      # - name: Install Dependencies
      #   run: |
      #     cd server && npm install &
      #     cd web && npm install &

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: |
            npm run start-server
            npm run start-web-client

          wait-on: 'http://localhost:3000, http://localhost:8080'
    env:
      browser: chrome
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
